name: main
on:
  push:
    branches:
      - main
  release:
    types: [published]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NPM Dependencies
        run: npm install
      - name: Setup git user
        run: |
          git config user.name "GitHub Action"
          git config user.email "github_action@local"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build App
        run: npm run deploy